export const commandIds = [
  'focusFirst',
  'focusIndex',
  'focusLast',
  'focusNext',
  'focusPrevious',
  'handleBeforeInput',
  'handleBlur',
  'handleClickAt',
  'handleInput',
  'handleWheel',
  'dispose',
  'renderEventListeners',
  'selectCurrentIndex',
  'selectIndex',
  'selectItem',
  'setValue',
]
