export const HandleBeforeInput = 'handleBeforeInput'
export const HandleBlur = 'handleBlur'
export const HandleFocus = 'handleFocus'
export const HandleInput = 'handleInput'
export const HandlePointerDown = 'handlePointerDown'
export const HandleWheel = 'handleWheel'
